[allowlist]
  description = "Ignore generated and dependency artifacts"
  commits = [
    "deb404c5a470f6e05d5cbbfbb9435f41495faa12",
  ]
  paths = [
    '''^node_modules/''',
    '''^dist/''',
    '''^coverage/''',
    '''^reports/''',
    '''^apps/.*/coverage/''',
    '''^apps/.*/dist/''',
    '''^packages/.*/dist/''',
    '''^apps/.*/.turbo/''',
    '''^\.pnpm/''',
    '''^\.turbo/''',
    '''^\.next/''',
    '''^out/''',
    '''^tmp/'''
  ]
