packages:
  - "apps/*"
  - "apps/**"
  - "!apps/**/.lumi-next/**"
  - "!apps/**/.next/**"
  - "!apps/**/.next-build/**"
  - "packages/*"
  - "packages/**"
  - "tools/*"
  - "tools/**"
  - "docs/*"
  - "docs/**"
