global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: cadvisor
    metrics_path: /metrics
    static_configs:
      - targets:
          - cadvisor:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: cadvisor

  - job_name: backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend:4000
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: backend
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: ".*"
        action: keep
